# Generated by Django 4.2.10 on 2024-02-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        ('articles', '0006_venue_article_venues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.AlterField(
            model_name='article',
            name='venues',
            field=models.ManyToManyField(related_name='articles', to='venues.venue'),
        ),
    ]
